---
apiVersion: apps/v1
Kind: Deployment
metadata: 
   name: spc
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels: 
       app: jenkins
  strategy:
    type: rollingUpdate
    maxSurge: 25%
    maxUnavailable: 25%
  template:
    metadata:
      name: spc
      labels:
        app: spc
  spec:
    containers:
      - name: spc-container
        image: shravanipranay/spc:latest
        ports:
          - containerPort: 8080
        livenessProbe:
            exec:
              command:
                - sleep 10
---
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - name: spc-port 
      port: 8080
      targetPort: 8080
      protocol: TCP
